name: Update hash in index-game.js

on:
  push:
    branches:
      - main

jobs:
  update-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get last commit and author
        id: commit
        run: |
          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
      - name: Stop if author is bot
        if: steps.commit.outputs.author == 'github-actions[bot]'
        run: |
          echo "Latest commit is from bot, skipping."
          exit 0
      - name: Replace commit in index-game.js
        run: |
          HASH=${{ steps.commit.outputs.hash }}
          FILE="assets/scripts/index-game.js"
          sed -i -E "s|window\.currentCommit = \".*\";|window.currentCommit = \"${HASH}\";|g" "$FILE"
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/scripts/index-game.js
          git diff --cached --quiet || git commit -m "Update currentCommit to ${{ steps.commit.outputs.hash }}"
          git push